import {motion} from 'framer-motion'
import {AlertTriangle, CheckCircle2, Loader2, RefreshCw, ShieldAlert} from 'lucide-react'
import {riskTone,titleCase} from './uiHelpers'
export function Panel({children,className=''}){return <div className={`glass rounded-2xl ${className}`}>{children}</div>}
export function StatCard({label,value,icon:Icon,accent='cyan',sub}){return <motion.div whileHover={{y:-2}} className="glass rounded-2xl p-5"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-[.18em] text-slate-500">{label}</p><p className="mt-2 text-3xl font-semibold tracking-tight">{value}</p>{sub&&<p className="mt-1 text-xs text-slate-500">{sub}</p>}</div>{Icon&&<div className={`rounded-xl border border-${accent}-400/20 bg-${accent}-400/10 p-3`}><Icon size={20}/></div>}</div></motion.div>}
export function Badge({level}){return <span className={`inline-flex rounded-full border px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider ${riskTone(level)}`}>{titleCase(level)}</span>}
export function LoadingSpinner({text='Loading...'}){return <div className="flex min-h-40 items-center justify-center gap-3 text-slate-400"><Loader2 className="animate-spin" size={18}/>{text}</div>}
export function ErrorState({message,onRetry}){return <div className="glass flex min-h-40 flex-col items-center justify-center gap-3 rounded-2xl text-center"><AlertTriangle className="text-red-300"/><p className="text-sm text-slate-300">{message}</p>{onRetry&&<button onClick={onRetry} className="btn-secondary"><RefreshCw size={15}/> Retry</button>}</div>}
export function EmptyState({text='No events yet.'}){return <div className="flex min-h-32 items-center justify-center text-sm text-slate-500">{text}</div>}
export function ResultBanner({result}){if(!result)return null;return <div className="glass rounded-2xl border border-cyan-400/20 p-5"><div className="flex flex-wrap items-center gap-3"><ShieldAlert className="text-cyan-300"/><div><p className="text-xs uppercase tracking-widest text-slate-500">Analysis Result</p><h3 className="text-xl font-semibold">{titleCase(result.prediction)}</h3></div><div className="ml-auto"><Badge level={result.risk_level}/></div></div></div>}

export function AlertToast({alert,onClose}){if(!alert)return null;return <div className="fixed bottom-5 right-5 z-[100] w-[min(380px,calc(100vw-2rem))] rounded-2xl border border-red-400/20 bg-[#0b1220]/95 p-4 shadow-2xl backdrop-blur-xl"><div className="flex gap-3"><ShieldAlert className="mt-0.5 text-red-300" size={20}/><div className="min-w-0 flex-1"><p className="text-[10px] font-bold uppercase tracking-widest text-red-300">{alert.risk_level} alert</p><p className="mt-1 text-sm font-medium text-slate-200">{alert.threat_type}</p><p className="mt-1 text-xs leading-5 text-slate-500">{alert.message}</p></div><button onClick={onClose} className="text-slate-500 hover:text-white">×</button></div></div>}
